<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TAisYn_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tAisYn.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tAisYn.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.tAisYn..App\\Entity\\Admin', NULL, 'Cannot autowire service ".service_locator.tAisYn.": it references class "App\\Entity\\Admin" but no such service exists.'],
        ], [
            'encoder' => '?',
            'manager' => '?',
            'user' => 'App\\Entity\\Admin',
        ]);
    }
}
