<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MjD1tSfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mjD1tSf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mjD1tSf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'films' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService', true],
        ], [
            'films' => 'App\\Repository\\FilmRepository',
        ]);
    }
}
