<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VBSjXZLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VBSjXZL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VBSjXZL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::removeUsers' => ['privates', '.service_locator.ojMcr9a', 'get_ServiceLocator_OjMcr9aService', true],
            'App\\Controller\\AdminController::showAdmin' => ['privates', '.service_locator.JADdnea', 'get_ServiceLocator_JADdneaService', true],
            'App\\Controller\\AdminController::switchRole' => ['privates', '.service_locator.e8S_KgE', 'get_ServiceLocator_E8SKgEService', true],
            'App\\Controller\\FilmController::discoverFilm' => ['privates', '.service_locator.mjD1tSf', 'get_ServiceLocator_MjD1tSfService', true],
            'App\\Controller\\HomeController::createUser' => ['privates', '.service_locator.GlxlSC0', 'get_ServiceLocator_GlxlSC0Service', true],
            'App\\Controller\\HomeController::deleteUser' => ['privates', '.service_locator.YGvaKKw', 'get_ServiceLocator_YGvaKKwService', true],
            'App\\Controller\\HomeController::editUser' => ['privates', '.service_locator.tAisYn.', 'get_ServiceLocator_TAisYn_Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:removeUsers' => ['privates', '.service_locator.ojMcr9a', 'get_ServiceLocator_OjMcr9aService', true],
            'App\\Controller\\AdminController:showAdmin' => ['privates', '.service_locator.JADdnea', 'get_ServiceLocator_JADdneaService', true],
            'App\\Controller\\AdminController:switchRole' => ['privates', '.service_locator.e8S_KgE', 'get_ServiceLocator_E8SKgEService', true],
            'App\\Controller\\FilmController:discoverFilm' => ['privates', '.service_locator.mjD1tSf', 'get_ServiceLocator_MjD1tSfService', true],
            'App\\Controller\\HomeController:createUser' => ['privates', '.service_locator.GlxlSC0', 'get_ServiceLocator_GlxlSC0Service', true],
            'App\\Controller\\HomeController:deleteUser' => ['privates', '.service_locator.YGvaKKw', 'get_ServiceLocator_YGvaKKwService', true],
            'App\\Controller\\HomeController:editUser' => ['privates', '.service_locator.tAisYn.', 'get_ServiceLocator_TAisYn_Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::removeUsers' => '?',
            'App\\Controller\\AdminController::showAdmin' => '?',
            'App\\Controller\\AdminController::switchRole' => '?',
            'App\\Controller\\FilmController::discoverFilm' => '?',
            'App\\Controller\\HomeController::createUser' => '?',
            'App\\Controller\\HomeController::deleteUser' => '?',
            'App\\Controller\\HomeController::editUser' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:removeUsers' => '?',
            'App\\Controller\\AdminController:showAdmin' => '?',
            'App\\Controller\\AdminController:switchRole' => '?',
            'App\\Controller\\FilmController:discoverFilm' => '?',
            'App\\Controller\\HomeController:createUser' => '?',
            'App\\Controller\\HomeController:deleteUser' => '?',
            'App\\Controller\\HomeController:editUser' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
