<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tAisYn..App\Entity\Admin' shared service.
     *
     * @return \App\Entity\Admin
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tAisYn.": it references class "App\\Entity\\Admin" but no such service exists.');
    }
}
