<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Feedback\FeedbackController' shared autowired service.
     *
     * @return \App\Controller\Feedback\FeedbackController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Feedback/FeedbackController.php';

        $container->services['App\\Controller\\Feedback\\FeedbackController'] = $instance = new \App\Controller\Feedback\FeedbackController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Feedback\\FeedbackController', $container));

        return $instance;
    }
}
