<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FilmController' shared autowired service.
     *
     * @return \App\Controller\FilmController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FilmController.php';

        $container->services['App\\Controller\\FilmController'] = $instance = new \App\Controller\FilmController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\FilmController', $container));

        return $instance;
    }
}
