<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifier_Channel_ChatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'notifier.channel.chat' shared service.
     *
     * @return \Symfony\Component\Notifier\Channel\ChatChannel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/ChannelInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/AbstractChannel.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/ChatChannel.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Transport/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Transport/Transports.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Transport.php';

        return $container->privates['notifier.channel.chat'] = new \Symfony\Component\Notifier\Channel\ChatChannel((new \Symfony\Component\Notifier\Transport(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['notifier.transport_factory.null'] ?? $container->load('getNotifier_TransportFactory_NullService'));
        }, 1)))->fromStrings([]), NULL);
    }
}
