<?php

namespace ContainerLHDLPEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'notifier' shared service.
     *
     * @return \Symfony\Component\Notifier\Notifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/NotifierInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Notifier.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/ChannelPolicyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/ChannelPolicy.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Recipient/Recipient.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Recipient/SmsRecipientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Recipient/AdminRecipient.php';

        $container->privates['notifier'] = $instance = new \Symfony\Component\Notifier\Notifier(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'browser' => ['privates', 'notifier.channel.browser', 'getNotifier_Channel_BrowserService', true],
            'chat' => ['privates', 'notifier.channel.chat', 'getNotifier_Channel_ChatService', true],
            'email' => ['privates', 'notifier.channel.email', 'getNotifier_Channel_EmailService', true],
            'sms' => ['privates', 'notifier.channel.sms', 'getNotifier_Channel_SmsService', true],
        ], [
            'browser' => 'Symfony\\Component\\Notifier\\Channel\\BrowserChannel',
            'chat' => 'Symfony\\Component\\Notifier\\Channel\\ChatChannel',
            'email' => 'Symfony\\Component\\Notifier\\Channel\\EmailChannel',
            'sms' => 'Symfony\\Component\\Notifier\\Channel\\SmsChannel',
        ]), new \Symfony\Component\Notifier\Channel\ChannelPolicy(['urgent' => [0 => 'email'], 'high' => [0 => 'email'], 'medium' => [0 => 'email'], 'low' => [0 => 'email']]));

        $instance->addAdminRecipient(new \Symfony\Component\Notifier\Recipient\AdminRecipient('admin@example.com', ''));

        return $instance;
    }
}
