<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHDLPEJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHDLPEJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHDLPEJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHDLPEJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHDLPEJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHDLPEJ',
    'container.build_id' => '45bad636',
    'container.build_time' => 1598003744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHDLPEJ');
