<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [['_locale'], ['_controller' => 'App\\Controller\\AdminController::showAdmin'], ['_locale' => 'en|fr'], [['text', '/admin'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'user.remove.all' => [['_locale'], ['_controller' => 'App\\Controller\\AdminController::removeUsers'], ['_locale' => 'en|fr'], [['text', '/removeusers'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'changerole' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\AdminController::switchRole'], ['_locale' => 'en|fr'], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/change'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'feedback' => [['_locale'], ['_controller' => 'App\\Controller\\Feedback\\FeedbackController::index'], ['_locale' => 'en|fr'], [['text', '/feedback'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'film.discover' => [['_locale'], ['_controller' => 'App\\Controller\\FilmController::discoverFilm'], ['_locale' => 'en|fr'], [['text', '/film'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_home_redirecthome' => [[], ['_controller' => 'App\\Controller\\HomeController::redirectHome'], [], [['text', '/']], [], []],
    'app_home_redirectlocalehome' => [['_locale'], ['_controller' => 'App\\Controller\\HomeController::redirectLocaleHome'], ['_locale' => 'en|fr'], [['text', '/'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'homepage' => [['_locale'], ['_controller' => 'App\\Controller\\HomeController::showHome'], ['_locale' => 'en|fr'], [['text', '/home'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'register_user' => [['_locale'], ['_controller' => 'App\\Controller\\HomeController::createUser'], ['_locale' => 'en|fr'], [['text', '/register'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'user_show' => [['_locale'], ['_controller' => 'App\\Controller\\HomeController::index'], ['_locale' => 'en|fr'], [['text', '/user'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'user_delete' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\HomeController::deleteUser'], ['_locale' => 'en|fr'], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/delete'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'user_edit' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\HomeController::editUser'], ['_locale' => 'en|fr'], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/edit'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_login' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::login'], ['_locale' => 'en|fr'], [['text', '/login'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
